import type { NextApiRequest, NextApiResponse } from 'next'
import bcrypt from 'bcryptjs'
import { supabaseAdmin } from '@/lib/supabase-admin'
import { ADMIN_SESSION_COOKIE, createAdminSessionToken } from '@/lib/admin-session'

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })
  const { email, password } = req.body || {}
  if (!email || !password) return res.status(400).json({ error: 'Email and password are required' })

  // Trim whitespace (browser autofill can add trailing spaces)
  const cleanEmail = String(email).trim().toLowerCase()
  const cleanPassword = String(password)

  try {
    const { data: admin, error } = await supabaseAdmin
      .from('admins')
      .select('*')
      .eq('email', cleanEmail)
      .single()

    if (error || !admin) {
      console.log(`[Login] No admin found for email: ${cleanEmail}`)
      return res.status(401).json({ error: 'Invalid credentials' })
    }

    // Normalize hash prefix: convert PHP-style $2y$ to $2b$ for bcryptjs compatibility
    let storedHash = admin.password_hash
    if (storedHash.startsWith('$2y$')) {
      storedHash = '$2b$' + storedHash.slice(4)
    }

    const ok = await bcrypt.compare(cleanPassword, storedHash)
    if (!ok) {
      console.log(`[Login] Password mismatch for: ${cleanEmail}`)
      return res.status(401).json({ error: 'Invalid credentials' })
    }

    // Hash migration: re-hash with current bcryptjs version so future logins
    // always use a hash generated by the installed library version.
    // This silently fixes old/incompatible hashes on successful login.
    try {
      const freshHash = await bcrypt.hash(cleanPassword, 10)
      await supabaseAdmin
        .from('admins')
        .update({ password_hash: freshHash })
        .eq('id', admin.id)
      console.log(`[Login] Migrated password hash for: ${cleanEmail}`)
    } catch (rehashErr) {
      // Non-fatal: login still succeeds even if re-hash update fails
      console.warn(`[Login] Hash migration failed for ${cleanEmail}:`, rehashErr)
    }

    const token = createAdminSessionToken(admin.id)
    res.setHeader('Set-Cookie', `${ADMIN_SESSION_COOKIE}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=86400`)
    return res.status(200).json({ success: true, admin: { id: admin.id, email: admin.email, name: admin.name || 'Admin' } })
  } catch (err) {
    console.error('[Login] Unexpected error:', err)
    return res.status(500).json({ error: 'Login failed' })
  }
}
